### ISSUE TITLE
godot-plugin-calendar-button - Translation to German

### ISSUE THREAD

**Issue by havi05** [jospic/godot3_shaders#2]
Sorry, but I can only write here.
I have translated the calendar-button to german.
It was not so diffiult. If you want to add the translation here are the codes:

german.json   (in the languages folder)
`{
    "Jan"      :"Jan",
    "Feb"      :"Feb", 
    "Mar"      :"Mär",
    "Apr"      :"Apr",
    "May"      :"Mai", 
    "Jun"      :"Jun", 
    "Jul"      :"Jul", 
    "Aug"      :"Aug", 
    "Sep"      :"Sep", 
    "Oct"      :"Okt", 
    "Nov"      :"Nov", 
    "Dec"      :"Dez",
    "Sunday"   :"Sonntag"   , 
    "Monday"   :"Montag"   , 
    "Tuesday"  :"Dienstag"  , 
    "Wednesday":"Mittwoch", 
    "Thursday" :"Donnerstag" , 
    "Friday"   :"Freitag"   , 
    "Saturday" :"Samstag" 
}`

calendar_script.gd  (in the main folder)
`row 50 :  export (String, "English", "Italian", "German") var language = "English"`

Thanks for transform to 3.x, i like this addon.
Gamemap

**Comment by jospic** [comment]
Thanks,
I've updated on repo.
-j
